/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.lrc.liferay.ram.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.lrc.liferay.ram.model.Assessment;
import com.lrc.liferay.ram.service.AssessmentLocalServiceUtil;

/**
 * The extended model base implementation for the Assessment service. Represents a row in the &quot;lrc_ram_Assessment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssessmentImpl}.
 * </p>
 *
 * @author fsuarezj
 * @see AssessmentImpl
 * @see com.lrc.liferay.ram.model.Assessment
 * @generated
 */
public abstract class AssessmentBaseImpl extends AssessmentModelImpl
	implements Assessment {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a assessment model instance should use the {@link Assessment} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			AssessmentLocalServiceUtil.addAssessment(this);
		}
		else {
			AssessmentLocalServiceUtil.updateAssessment(this);
		}
	}
}