/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lrc.liferay.toolbuilder.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import org.lrc.liferay.toolbuilder.model.ToolInstance;
import org.lrc.liferay.toolbuilder.service.ToolInstanceService;
import org.lrc.liferay.toolbuilder.service.persistence.ToolInstancePersistence;
import org.lrc.liferay.toolbuilder.service.persistence.WrapperStepPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the tool instance remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.lrc.liferay.toolbuilder.service.impl.ToolInstanceServiceImpl}.
 * </p>
 *
 * @author Fernando Suárez
 * @see org.lrc.liferay.toolbuilder.service.impl.ToolInstanceServiceImpl
 * @see org.lrc.liferay.toolbuilder.service.ToolInstanceServiceUtil
 * @generated
 */
public abstract class ToolInstanceServiceBaseImpl extends BaseServiceImpl
	implements ToolInstanceService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link org.lrc.liferay.toolbuilder.service.ToolInstanceServiceUtil} to access the tool instance remote service.
	 */

	/**
	 * Returns the tool instance local service.
	 *
	 * @return the tool instance local service
	 */
	public org.lrc.liferay.toolbuilder.service.ToolInstanceLocalService getToolInstanceLocalService() {
		return toolInstanceLocalService;
	}

	/**
	 * Sets the tool instance local service.
	 *
	 * @param toolInstanceLocalService the tool instance local service
	 */
	public void setToolInstanceLocalService(
		org.lrc.liferay.toolbuilder.service.ToolInstanceLocalService toolInstanceLocalService) {
		this.toolInstanceLocalService = toolInstanceLocalService;
	}

	/**
	 * Returns the tool instance remote service.
	 *
	 * @return the tool instance remote service
	 */
	public org.lrc.liferay.toolbuilder.service.ToolInstanceService getToolInstanceService() {
		return toolInstanceService;
	}

	/**
	 * Sets the tool instance remote service.
	 *
	 * @param toolInstanceService the tool instance remote service
	 */
	public void setToolInstanceService(
		org.lrc.liferay.toolbuilder.service.ToolInstanceService toolInstanceService) {
		this.toolInstanceService = toolInstanceService;
	}

	/**
	 * Returns the tool instance persistence.
	 *
	 * @return the tool instance persistence
	 */
	public ToolInstancePersistence getToolInstancePersistence() {
		return toolInstancePersistence;
	}

	/**
	 * Sets the tool instance persistence.
	 *
	 * @param toolInstancePersistence the tool instance persistence
	 */
	public void setToolInstancePersistence(
		ToolInstancePersistence toolInstancePersistence) {
		this.toolInstancePersistence = toolInstancePersistence;
	}

	/**
	 * Returns the wrapper step local service.
	 *
	 * @return the wrapper step local service
	 */
	public org.lrc.liferay.toolbuilder.service.WrapperStepLocalService getWrapperStepLocalService() {
		return wrapperStepLocalService;
	}

	/**
	 * Sets the wrapper step local service.
	 *
	 * @param wrapperStepLocalService the wrapper step local service
	 */
	public void setWrapperStepLocalService(
		org.lrc.liferay.toolbuilder.service.WrapperStepLocalService wrapperStepLocalService) {
		this.wrapperStepLocalService = wrapperStepLocalService;
	}

	/**
	 * Returns the wrapper step remote service.
	 *
	 * @return the wrapper step remote service
	 */
	public org.lrc.liferay.toolbuilder.service.WrapperStepService getWrapperStepService() {
		return wrapperStepService;
	}

	/**
	 * Sets the wrapper step remote service.
	 *
	 * @param wrapperStepService the wrapper step remote service
	 */
	public void setWrapperStepService(
		org.lrc.liferay.toolbuilder.service.WrapperStepService wrapperStepService) {
		this.wrapperStepService = wrapperStepService;
	}

	/**
	 * Returns the wrapper step persistence.
	 *
	 * @return the wrapper step persistence
	 */
	public WrapperStepPersistence getWrapperStepPersistence() {
		return wrapperStepPersistence;
	}

	/**
	 * Sets the wrapper step persistence.
	 *
	 * @param wrapperStepPersistence the wrapper step persistence
	 */
	public void setWrapperStepPersistence(
		WrapperStepPersistence wrapperStepPersistence) {
		this.wrapperStepPersistence = wrapperStepPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return ToolInstance.class;
	}

	protected String getModelClassName() {
		return ToolInstance.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = toolInstancePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = org.lrc.liferay.toolbuilder.service.ToolInstanceLocalService.class)
	protected org.lrc.liferay.toolbuilder.service.ToolInstanceLocalService toolInstanceLocalService;
	@BeanReference(type = org.lrc.liferay.toolbuilder.service.ToolInstanceService.class)
	protected org.lrc.liferay.toolbuilder.service.ToolInstanceService toolInstanceService;
	@BeanReference(type = ToolInstancePersistence.class)
	protected ToolInstancePersistence toolInstancePersistence;
	@BeanReference(type = org.lrc.liferay.toolbuilder.service.WrapperStepLocalService.class)
	protected org.lrc.liferay.toolbuilder.service.WrapperStepLocalService wrapperStepLocalService;
	@BeanReference(type = org.lrc.liferay.toolbuilder.service.WrapperStepService.class)
	protected org.lrc.liferay.toolbuilder.service.WrapperStepService wrapperStepService;
	@BeanReference(type = WrapperStepPersistence.class)
	protected WrapperStepPersistence wrapperStepPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private ToolInstanceServiceClpInvoker _clpInvoker = new ToolInstanceServiceClpInvoker();
}