/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lrc.liferay.toolbuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the InstalledSteps service. Represents a row in the &quot;lrc_tb_InstalledSteps&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.lrc.liferay.toolbuilder.model.impl.InstalledStepsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.lrc.liferay.toolbuilder.model.impl.InstalledStepsImpl}.
 * </p>
 *
 * @author Fernando Suárez
 * @see InstalledSteps
 * @see org.lrc.liferay.toolbuilder.model.impl.InstalledStepsImpl
 * @see org.lrc.liferay.toolbuilder.model.impl.InstalledStepsModelImpl
 * @generated
 */
public interface InstalledStepsModel extends BaseModel<InstalledSteps>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a installed steps model instance should use the {@link InstalledSteps} interface instead.
	 */

	/**
	 * Returns the primary key of this installed steps.
	 *
	 * @return the primary key of this installed steps
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this installed steps.
	 *
	 * @param primaryKey the primary key of this installed steps
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the type of this installed steps.
	 *
	 * @return the type of this installed steps
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this installed steps.
	 *
	 * @param type the type of this installed steps
	 */
	public void setType(String type);

	/**
	 * Returns the group ID of this installed steps.
	 *
	 * @return the group ID of this installed steps
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this installed steps.
	 *
	 * @param groupId the group ID of this installed steps
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this installed steps.
	 *
	 * @return the company ID of this installed steps
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this installed steps.
	 *
	 * @param companyId the company ID of this installed steps
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this installed steps.
	 *
	 * @return the user ID of this installed steps
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this installed steps.
	 *
	 * @param userId the user ID of this installed steps
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this installed steps.
	 *
	 * @return the user uuid of this installed steps
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this installed steps.
	 *
	 * @param userUuid the user uuid of this installed steps
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this installed steps.
	 *
	 * @return the user name of this installed steps
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this installed steps.
	 *
	 * @param userName the user name of this installed steps
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this installed steps.
	 *
	 * @return the create date of this installed steps
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this installed steps.
	 *
	 * @param createDate the create date of this installed steps
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this installed steps.
	 *
	 * @return the modified date of this installed steps
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this installed steps.
	 *
	 * @param modifiedDate the modified date of this installed steps
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the namespace of this installed steps.
	 *
	 * @return the namespace of this installed steps
	 */
	@AutoEscape
	public String getNamespace();

	/**
	 * Sets the namespace of this installed steps.
	 *
	 * @param namespace the namespace of this installed steps
	 */
	public void setNamespace(String namespace);

	/**
	 * Returns the class name of this installed steps.
	 *
	 * @return the class name of this installed steps
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this installed steps.
	 *
	 * @param className the class name of this installed steps
	 */
	public void setClassName(String className);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.lrc.liferay.toolbuilder.model.InstalledSteps installedSteps);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.lrc.liferay.toolbuilder.model.InstalledSteps> toCacheModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.InstalledSteps toEscapedModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.InstalledSteps toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}