/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lrc.liferay.toolbuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Instance service. Represents a row in the &quot;lrc_tb_Instance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.lrc.liferay.toolbuilder.model.impl.InstanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.lrc.liferay.toolbuilder.model.impl.InstanceImpl}.
 * </p>
 *
 * @author Fernando Suárez
 * @see Instance
 * @see org.lrc.liferay.toolbuilder.model.impl.InstanceImpl
 * @see org.lrc.liferay.toolbuilder.model.impl.InstanceModelImpl
 * @generated
 */
public interface InstanceModel extends BaseModel<Instance>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a instance model instance should use the {@link Instance} interface instead.
	 */

	/**
	 * Returns the primary key of this instance.
	 *
	 * @return the primary key of this instance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this instance.
	 *
	 * @param primaryKey the primary key of this instance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the instance ID of this instance.
	 *
	 * @return the instance ID of this instance
	 */
	public long getInstanceId();

	/**
	 * Sets the instance ID of this instance.
	 *
	 * @param instanceId the instance ID of this instance
	 */
	public void setInstanceId(long instanceId);

	/**
	 * Returns the group ID of this instance.
	 *
	 * @return the group ID of this instance
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this instance.
	 *
	 * @param groupId the group ID of this instance
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this instance.
	 *
	 * @return the company ID of this instance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this instance.
	 *
	 * @param companyId the company ID of this instance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this instance.
	 *
	 * @return the user ID of this instance
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this instance.
	 *
	 * @param userId the user ID of this instance
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this instance.
	 *
	 * @return the user uuid of this instance
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this instance.
	 *
	 * @param userUuid the user uuid of this instance
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this instance.
	 *
	 * @return the user name of this instance
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this instance.
	 *
	 * @param userName the user name of this instance
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this instance.
	 *
	 * @return the create date of this instance
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this instance.
	 *
	 * @param createDate the create date of this instance
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this instance.
	 *
	 * @return the modified date of this instance
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this instance.
	 *
	 * @param modifiedDate the modified date of this instance
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this instance.
	 *
	 * @return the name of this instance
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this instance.
	 *
	 * @param name the name of this instance
	 */
	public void setName(String name);

	/**
	 * Returns the step of this instance.
	 *
	 * @return the step of this instance
	 */
	public int getStep();

	/**
	 * Sets the step of this instance.
	 *
	 * @param step the step of this instance
	 */
	public void setStep(int step);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(org.lrc.liferay.toolbuilder.model.Instance instance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.lrc.liferay.toolbuilder.model.Instance> toCacheModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.Instance toEscapedModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.Instance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}