/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lrc.liferay.toolbuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ToolInstance service. Represents a row in the &quot;lrc_tb_ToolInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.lrc.liferay.toolbuilder.model.impl.ToolInstanceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.lrc.liferay.toolbuilder.model.impl.ToolInstanceImpl}.
 * </p>
 *
 * @author Fernando Suárez
 * @see ToolInstance
 * @see org.lrc.liferay.toolbuilder.model.impl.ToolInstanceImpl
 * @see org.lrc.liferay.toolbuilder.model.impl.ToolInstanceModelImpl
 * @generated
 */
public interface ToolInstanceModel extends BaseModel<ToolInstance>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tool instance model instance should use the {@link ToolInstance} interface instead.
	 */

	/**
	 * Returns the primary key of this tool instance.
	 *
	 * @return the primary key of this tool instance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tool instance.
	 *
	 * @param primaryKey the primary key of this tool instance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the group ID of this tool instance.
	 *
	 * @return the group ID of this tool instance
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tool instance.
	 *
	 * @param groupId the group ID of this tool instance
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tool instance.
	 *
	 * @return the company ID of this tool instance
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tool instance.
	 *
	 * @param companyId the company ID of this tool instance
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tool instance.
	 *
	 * @return the user ID of this tool instance
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tool instance.
	 *
	 * @param userId the user ID of this tool instance
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tool instance.
	 *
	 * @return the user uuid of this tool instance
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tool instance.
	 *
	 * @param userUuid the user uuid of this tool instance
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tool instance.
	 *
	 * @return the user name of this tool instance
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tool instance.
	 *
	 * @param userName the user name of this tool instance
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tool instance.
	 *
	 * @return the create date of this tool instance
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tool instance.
	 *
	 * @param createDate the create date of this tool instance
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tool instance.
	 *
	 * @return the modified date of this tool instance
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tool instance.
	 *
	 * @param modifiedDate the modified date of this tool instance
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this tool instance.
	 *
	 * @return the name of this tool instance
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this tool instance.
	 *
	 * @param name the name of this tool instance
	 */
	public void setName(String name);

	/**
	 * Returns the tool instance ID of this tool instance.
	 *
	 * @return the tool instance ID of this tool instance
	 */
	public long getToolInstanceId();

	/**
	 * Sets the tool instance ID of this tool instance.
	 *
	 * @param toolInstanceId the tool instance ID of this tool instance
	 */
	public void setToolInstanceId(long toolInstanceId);

	/**
	 * Returns the wrapper step ID of this tool instance.
	 *
	 * @return the wrapper step ID of this tool instance
	 */
	public long getWrapperStepId();

	/**
	 * Sets the wrapper step ID of this tool instance.
	 *
	 * @param wrapperStepId the wrapper step ID of this tool instance
	 */
	public void setWrapperStepId(long wrapperStepId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.lrc.liferay.toolbuilder.model.ToolInstance toolInstance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.lrc.liferay.toolbuilder.model.ToolInstance> toCacheModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.ToolInstance toEscapedModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.ToolInstance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}