/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lrc.liferay.toolbuilder.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the WrapperStepDBE service. Represents a row in the &quot;lrc_tb_WrapperStepDBE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.lrc.liferay.toolbuilder.model.impl.WrapperStepDBEModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.lrc.liferay.toolbuilder.model.impl.WrapperStepDBEImpl}.
 * </p>
 *
 * @author Fernando Suárez
 * @see WrapperStepDBE
 * @see org.lrc.liferay.toolbuilder.model.impl.WrapperStepDBEImpl
 * @see org.lrc.liferay.toolbuilder.model.impl.WrapperStepDBEModelImpl
 * @generated
 */
public interface WrapperStepDBEModel extends BaseModel<WrapperStepDBE> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wrapper step d b e model instance should use the {@link WrapperStepDBE} interface instead.
	 */

	/**
	 * Returns the primary key of this wrapper step d b e.
	 *
	 * @return the primary key of this wrapper step d b e
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wrapper step d b e.
	 *
	 * @param primaryKey the primary key of this wrapper step d b e
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the wrapper step d b e ID of this wrapper step d b e.
	 *
	 * @return the wrapper step d b e ID of this wrapper step d b e
	 */
	public long getWrapperStepDBEId();

	/**
	 * Sets the wrapper step d b e ID of this wrapper step d b e.
	 *
	 * @param wrapperStepDBEId the wrapper step d b e ID of this wrapper step d b e
	 */
	public void setWrapperStepDBEId(long wrapperStepDBEId);

	/**
	 * Returns the current step of this wrapper step d b e.
	 *
	 * @return the current step of this wrapper step d b e
	 */
	public int getCurrentStep();

	/**
	 * Sets the current step of this wrapper step d b e.
	 *
	 * @param currentStep the current step of this wrapper step d b e
	 */
	public void setCurrentStep(int currentStep);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.lrc.liferay.toolbuilder.model.WrapperStepDBE wrapperStepDBE);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.lrc.liferay.toolbuilder.model.WrapperStepDBE> toCacheModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.WrapperStepDBE toEscapedModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.WrapperStepDBE toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}