/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.lrc.liferay.toolbuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the WrapperStep service. Represents a row in the &quot;lrc_tb_WrapperStep&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.lrc.liferay.toolbuilder.model.impl.WrapperStepModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.lrc.liferay.toolbuilder.model.impl.WrapperStepImpl}.
 * </p>
 *
 * @author Fernando Suárez
 * @see WrapperStep
 * @see org.lrc.liferay.toolbuilder.model.impl.WrapperStepImpl
 * @see org.lrc.liferay.toolbuilder.model.impl.WrapperStepModelImpl
 * @generated
 */
public interface WrapperStepModel extends BaseModel<WrapperStep>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wrapper step model instance should use the {@link WrapperStep} interface instead.
	 */

	/**
	 * Returns the primary key of this wrapper step.
	 *
	 * @return the primary key of this wrapper step
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wrapper step.
	 *
	 * @param primaryKey the primary key of this wrapper step
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the wrapper step ID of this wrapper step.
	 *
	 * @return the wrapper step ID of this wrapper step
	 */
	public long getWrapperStepId();

	/**
	 * Sets the wrapper step ID of this wrapper step.
	 *
	 * @param wrapperStepId the wrapper step ID of this wrapper step
	 */
	public void setWrapperStepId(long wrapperStepId);

	/**
	 * Returns the group ID of this wrapper step.
	 *
	 * @return the group ID of this wrapper step
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this wrapper step.
	 *
	 * @param groupId the group ID of this wrapper step
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this wrapper step.
	 *
	 * @return the company ID of this wrapper step
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this wrapper step.
	 *
	 * @param companyId the company ID of this wrapper step
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this wrapper step.
	 *
	 * @return the user ID of this wrapper step
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this wrapper step.
	 *
	 * @param userId the user ID of this wrapper step
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this wrapper step.
	 *
	 * @return the user uuid of this wrapper step
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this wrapper step.
	 *
	 * @param userUuid the user uuid of this wrapper step
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this wrapper step.
	 *
	 * @return the user name of this wrapper step
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this wrapper step.
	 *
	 * @param userName the user name of this wrapper step
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this wrapper step.
	 *
	 * @return the create date of this wrapper step
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this wrapper step.
	 *
	 * @param createDate the create date of this wrapper step
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this wrapper step.
	 *
	 * @return the modified date of this wrapper step
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this wrapper step.
	 *
	 * @param modifiedDate the modified date of this wrapper step
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the current step of this wrapper step.
	 *
	 * @return the current step of this wrapper step
	 */
	public int getCurrentStep();

	/**
	 * Sets the current step of this wrapper step.
	 *
	 * @param currentStep the current step of this wrapper step
	 */
	public void setCurrentStep(int currentStep);

	/**
	 * Returns the sequential of this wrapper step.
	 *
	 * @return the sequential of this wrapper step
	 */
	public boolean getSequential();

	/**
	 * Returns <code>true</code> if this wrapper step is sequential.
	 *
	 * @return <code>true</code> if this wrapper step is sequential; <code>false</code> otherwise
	 */
	public boolean isSequential();

	/**
	 * Sets whether this wrapper step is sequential.
	 *
	 * @param sequential the sequential of this wrapper step
	 */
	public void setSequential(boolean sequential);

	/**
	 * Returns the steps number of this wrapper step.
	 *
	 * @return the steps number of this wrapper step
	 */
	public int getStepsNumber();

	/**
	 * Sets the steps number of this wrapper step.
	 *
	 * @param stepsNumber the steps number of this wrapper step
	 */
	public void setStepsNumber(int stepsNumber);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		org.lrc.liferay.toolbuilder.model.WrapperStep wrapperStep);

	@Override
	public int hashCode();

	@Override
	public CacheModel<org.lrc.liferay.toolbuilder.model.WrapperStep> toCacheModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.WrapperStep toEscapedModel();

	@Override
	public org.lrc.liferay.toolbuilder.model.WrapperStep toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}